# Generated by Django 5.1.3 on 2024-11-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
