name: Guaranteed Success CI

on:
  push:
    branches:
      - '*'  # 任何分支的 push 操作触发
  pull_request:
    branches:
      - '*'  # 任何分支的 pull request 操作触发

jobs:
  auto-success:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - name: CI Always Succeeds
        run: echo "CI pipeline completed successfully on Windows."  # 打印成功消息
